apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE}-config-${BUILD_TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
data:
  DEPLOYMENT_ENV: ${DEPLOYMENT_ENV}
